---
- import_playbook: /infrastructure/ansible/setup.yml
  vars:
    vault_addr: "{{ lookup('env','VAULT_ADDR') }}"

- import_playbook: /infrastructure/ansible/monitoring.yml
  vars:
    datadog_api_key: DUMMY_DATADOG_API_KEY_NOT_CONFIGURED
    network_id: unknown

- hosts: all
  remote_user: master
  become: yes
  vars:
    datadog_enabled: false
  tasks:
    - name: "Setup bootstrap on reboot (legacy)"
      lineinfile:
        path: /etc/cloud/cloud.cfg
        regexp: '^ - scripts-user'
        line: ' - [scripts-user, always]'
        backrefs: yes
        backup: yes
        # the original .cfg is missing #cloud-config header for some reason
        # validate: 'cloud-init schema --config-file %s'

    - name: "Setup bootstrap on reboot"
      lineinfile:
        path: /etc/cloud/cloud.cfg
        regexp: '^  - scripts_user'
        line: '  - [scripts_user, always]'
        backrefs: yes
        backup: yes
        # the original .cfg is missing #cloud-config header for some reason
        # validate: 'cloud-init schema --config-file %s'

    - name: "Stop and disable datadog services"
      service:
        name: "{{ item }}"
        enabled: false
        state: stopped
      with_items:
        - datadog-agent
        - datadog-agent-trace
        - datadog-agent-process
